name: custom smart pointers CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

# =================================== SHARED_PTR ===================================
      - name: Configure CMake -> shared_ptr
        run: |
          cd shared_ptr
          mkdir build
          cd build
          cmake ..

      - name: Build -> shared_ptr
        run: |
          cd shared_ptr/build
          cmake --build .

      - name: Running Tests -> shared_ptr
        run: |
          if [ ${{ matrix.os }} == 'windows-latest' ]; then
            cd shared_ptr/build/tests/Debug
            ./Tests.exe
          elif [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
            cd shared_ptr/build/tests
            ./Tests
          fi
        shell: bash

# =================================== UNIQUE_PTR ===================================
      - name: Configure CMake -> unique_ptr
        run: |
          cd unique_ptr
          mkdir build
          cd build
          cmake ..

      - name: Build -> unique_ptr
        run: |
          cd unique_ptr/build
          cmake --build .

      - name: Running Tests -> unique_ptr
        run: |
          if [ ${{ matrix.os }} == 'windows-latest' ]; then
            cd unique_ptr/build/tests/Debug
            ./Tests.exe
          elif [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
            cd unique_ptr/build/tests
            ./Tests
          fi
        shell: bash