name: custom smart pointers CI/CD

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

# =================================== SHARED_PTR ===================================
      - name: Clone googletest repository to shared_ptr
        run: |
          cd shared_ptr
          git clone https://github.com/google/googletest.git

      - name: Build shared_ptr CMake
        run: |
          cd shared_ptr
          mkdir build
          cd build
          cmake ..
          cmake --build .

      - name: Running shared_ptr Tests
        run: |
          if [ ${{ matrix.os }} == 'windows-latest' ]; then
            dir
            cd shared_ptr/build/tests/Debug
            ./Tests.exe
          elif [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
            ls
            cd shared_ptr/build/tests
            ./Tests
          fi
        shell: bash

# =================================== UNIQUE_PTR ===================================
      - name: Build unique_ptr CMake
        run: |
          cd unique_ptr
          mkdir build
          cd build
          cmake ..
          cmake --build .

      - name: Running unique_ptr Tests
        run: |
          if [ ${{ matrix.os }} == 'windows-latest' ]; then
            dir
            cd unique_ptr/build/tests/Debug
            ./Tests.exe
          elif [ ${{ matrix.os }} == 'ubuntu-latest' ]; then
            ls
            cd unique_ptr/build/tests
            ./Tests
          fi
        shell: bash