name: custom smart pointers CI/CD

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

# =================================== SHARED_PTR ===================================
      - name: Clone googletest repository to shared_ptr
        run: |
          cd shared_ptr
          git clone https://github.com/google/googletest.git

      - name: Build shared_ptr CMake
        run: |
          cd shared_ptr
          mkdir build
          cd build
          cmake ..
          cmake --build .

      - name: Running shared_ptr Tests
        run: |
            cd shared_ptr/build/tests
            ./Tests
        shell: bash

# =========================================================================================================